export enum StockState {
  AVAILABLE = 'AVAILABLE',
  RESERVED = 'RESERVED',
  PICKING = 'PICKING',
  IN_TRANSIT_INTERNAL = 'IN_TRANSIT_INTERNAL',
  QUARANTINE = 'QUARANTINE',
  SCRAP = 'SCRAP',
  BLOCKED = 'BLOCKED',
}
