ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "createdBy" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "updatedBy" TEXT;

ALTER TABLE "Role" ADD COLUMN IF NOT EXISTS "createdBy" TEXT;
ALTER TABLE "Role" ADD COLUMN IF NOT EXISTS "updatedBy" TEXT;

ALTER TABLE "Warehouse" ADD COLUMN IF NOT EXISTS "createdBy" TEXT;
ALTER TABLE "Warehouse" ADD COLUMN IF NOT EXISTS "updatedBy" TEXT;

ALTER TABLE "Location" ADD COLUMN IF NOT EXISTS "createdBy" TEXT;
ALTER TABLE "Location" ADD COLUMN IF NOT EXISTS "updatedBy" TEXT;

ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "createdBy" TEXT;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "updatedBy" TEXT;

ALTER TABLE "Batch" ADD COLUMN IF NOT EXISTS "createdBy" TEXT;
ALTER TABLE "Batch" ADD COLUMN IF NOT EXISTS "updatedBy" TEXT;

ALTER TABLE "Inventory" ADD COLUMN IF NOT EXISTS "createdBy" TEXT;
ALTER TABLE "Inventory" ADD COLUMN IF NOT EXISTS "updatedBy" TEXT;

ALTER TABLE "MovementHeader" ADD COLUMN IF NOT EXISTS "createdBy" TEXT;
ALTER TABLE "MovementHeader" ADD COLUMN IF NOT EXISTS "updatedBy" TEXT;

ALTER TABLE "MovementLine" ADD COLUMN IF NOT EXISTS "createdBy" TEXT;
ALTER TABLE "MovementLine" ADD COLUMN IF NOT EXISTS "updatedBy" TEXT;

ALTER TABLE "InboundReceipt" ADD COLUMN IF NOT EXISTS "createdBy" TEXT;
ALTER TABLE "InboundReceipt" ADD COLUMN IF NOT EXISTS "updatedBy" TEXT;

ALTER TABLE "InboundReceiptLine" ADD COLUMN IF NOT EXISTS "createdBy" TEXT;
ALTER TABLE "InboundReceiptLine" ADD COLUMN IF NOT EXISTS "updatedBy" TEXT;
